export const users = [
  {
    id: 1,
    userName: 'user11',
    Birthday: '1990-01-01',
    Email: 'user1@example.com',
    Phone: '+1234567891',
    Skype: 'skype.user1',
    AvatarUrl: 'https://source.unsplash.com/random/350x240?avatar',
  },
  {
    id: 2,
    userName: 'user22',
    Birthday: '1985-05-15',
    Email: 'user2@example.com',
    Phone: '+1234567892',
    Skype: 'skype.user2',
    AvatarUrl: 'https://source.unsplash.com/random/350x240?avatar',
  },
  {
    id: 3,
    userName: 'user33',
    Birthday: '1998-08-22',
    Email: 'user3@example.com',
    Phone: '+1234567893',
    Skype: 'skype.user3',
    AvatarUrl: 'https://source.unsplash.com/random/350x240?avatar',
  },
  {
    id: 4,
    userName: 'user44',
    Birthday: '1992-03-10',
    Email: 'user4@example.com',
    Phone: '+1234567894',
    Skype: 'skype.user4',
    AvatarUrl: 'https://source.unsplash.com/random/350x240?avatar',
  },
  {
    Id: 5,
    userName: 'user55',
    Birthday: '1987-11-30',
    Email: 'user5@example.com',
    Phone: '+1234567895',
    Skype: 'skype.user5',
    AvatarUrl: 'https://source.unsplash.com/random/350x240?avatar',
  },
];

export const tasks = [
  {
    id: 1,
    owner: 1,
    Title: 'Complete Project Proposal',
    Start: '10:00 AM',
    End: '3:00 PM',
    Priority: 'High',
    Date: '2023-08-25',
    Category: 'To do',
  },
  {
    id: 2,
    owner: 1,
    Title: 'Write Report',
    Start: '11:00 AM',
    End: '2:00 PM',
    Priority: 'Medium',
    Date: '2023-08-26',
    Category: 'In progress',
  },
  {
    id: 3,
    owner: 1,
    Title: 'Client Meeting',
    Start: '11:30 AM',
    End: '1:00 PM',
    Priority: 'High',
    Date: '2023-08-27',
    Category: 'Done',
  },
  // Другий користувач
  {
    id: 4,
    owner: 2,
    Title: 'Buy Groceries',
    Start: '9:00 AM',
    End: '10:30 AM',
    Priority: 'Medium',
    Date: '2023-08-25',
    Category: 'To do',
  },
  {
    id: 5,
    owner: 2,
    Title: 'Movie Night',
    Start: '7:30 PM',
    End: '10:00 PM',
    Priority: 'Low',
    Date: '2023-08-26',
    Category: 'In progress',
  },
  {
    id: 6,
    owner: 2,
    Title: 'Webinar',
    Start: '4:00 PM',
    End: '5:30 PM',
    Priority: 'Medium',
    Date: '2023-08-27',
    Category: 'Done',
  },
  // Третій користувач
  {
    id: 7,
    owner: 3,
    Title: 'Study for Exam',
    Start: '1:00 PM',
    End: '6:00 PM',
    Priority: 'High',
    Date: '2023-08-25',
    Category: 'To do',
  },
  {
    id: 8,
    owner: 3,
    Title: 'Prepare Presentation',
    Start: '9:00 AM',
    End: '12:00 PM',
    Priority: 'High',
    Date: '2023-08-26',
    Category: 'In progress',
  },
  {
    id: 9,
    owner: 3,
    Title: 'Review Code',
    Start: '10:00 AM',
    End: '12:00 PM',
    Priority: 'High',
    Date: '2023-08-27',
    Category: 'Done',
  },
  // Четвертий користувач
  {
    id: 10,
    owner: 4,
    Title: 'Call Client',
    Start: '2:30 PM',
    End: '3:15 PM',
    Priority: 'Medium',
    Date: '2023-08-25',
    Category: 'To do',
  },
  {
    id: 11,
    owner: 4,
    Title: 'Meet with Team',
    Start: '3:00 PM',
    End: '4:30 PM',
    Priority: 'High',
    Date: '2023-08-26',
    Category: 'In progress',
  },
  {
    id: 12,
    owner: 4,
    Title: 'Birthday Party',
    Start: '7:00 PM',
    End: '11:00 PM',
    Priority: 'Low',
    Date: '2023-08-27',
    Category: 'Done',
  },
  // П'ятий користувач
  {
    id: 13,
    owner: 5,
    Title: 'Exercise',
    Start: '7:00 AM',
    End: '8:00 AM',
    Priority: 'Low',
    Date: '2023-08-25',
    Category: 'To do',
  },
  {
    id: 14,
    owner: 5,
    Title: 'Read Articles',
    Start: '1:30 PM',
    End: '2:30 PM',
    Priority: 'Medium',
    Date: '2023-08-26',
    Category: 'In progress',
  },
  {
    id: 15,
    owner: 5,
    Title: 'Team Workshop',
    Start: '9:30 AM',
    End: '12:30 PM',
    Priority: 'High',
    Date: '2023-08-27',
    Category: 'Done',
  },
  {
    id: 16,
    owner: 1,
    Title: 'Client Meeting',
    Start: '2:30 PM',
    End: '4:00 PM',
    Priority: 'High',
    Date: '2023-08-25',
    Category: 'To do',
  },
  {
    id: 17,
    owner: 1,
    Title: 'Review Proposal',
    Start: '10:00 AM',
    End: '11:30 AM',
    Priority: 'Medium',
    Date: '2023-08-26',
    Category: 'In progress',
  },
  {
    id: 18,
    owner: 1,
    Title: 'Prepare Presentation',
    Start: '1:00 PM',
    End: '3:00 PM',
    Priority: 'High',
    Date: '2023-08-27',
    Category: 'Done',
  },
  // Другий користувач
  {
    id: 19,
    owner: 2,
    Title: 'Study for Exam',
    Start: '9:00 AM',
    End: '12:00 PM',
    Priority: 'High',
    Date: '2023-08-25',
    Category: 'To do',
  },
  {
    id: 20,
    owner: 2,
    Title: 'Write Blog Post',
    Start: '4:00 PM',
    End: '6:00 PM',
    Priority: 'Medium',
    Date: '2023-08-26',
    Category: 'In progress',
  },
  {
    id: 21,
    owner: 2,
    Title: 'Call Client',
    Start: '11:00 AM',
    End: '12:30 PM',
    Priority: 'High',
    Date: '2023-08-27',
    Category: 'Done',
  },
  // Третій користувач
  {
    id: 22,
    owner: 3,
    Title: 'Read a Book',
    Start: '7:00 PM',
    End: '8:30 PM',
    Priority: 'Low',
    Date: '2023-08-25',
    Category: 'To do',
  },
  {
    id: 23,
    owner: 3,
    Title: 'Exercise',
    Start: '6:00 AM',
    End: '7:00 AM',
    Priority: 'Low',
    Date: '2023-08-26',
    Category: 'In progress',
  },
  {
    id: 24,
    owner: 3,
    Title: 'Client Meeting',
    Start: '3:30 PM',
    End: '5:00 PM',
    Priority: 'High',
    Date: '2023-08-27',
    Category: 'Done',
  },
  // Четвертий користувач
  {
    id: 25,
    owner: 4,
    Title: 'Plan Vacation',
    Start: '10:00 AM',
    End: '12:00 PM',
    Priority: 'Medium',
    Date: '2023-08-25',
    Category: 'To do',
  },
  {
    id: 26,
    owner: 4,
    Title: 'Team Workshop',
    Start: '2:00 PM',
    End: '4:00 PM',
    Priority: 'High',
    Date: '2023-08-26',
    Category: 'In progress',
  },
  {
    id: 27,
    owner: 4,
    Title: 'Study New Technology',
    Start: '9:30 AM',
    End: '11:30 AM',
    Priority: 'High',
    Date: '2023-08-27',
    Category: 'Done',
  },
  // П'ятий користувач
  {
    id: 28,
    owner: 5,
    Title: 'Write Code',
    Start: '1:00 PM',
    End: '3:30 PM',
    Priority: 'Medium',
    Date: '2023-08-25',
    Category: 'To do',
  },
  {
    id: 29,
    owner: 5,
    Title: 'Family Dinner',
    Start: '6:30 PM',
    End: '8:00 PM',
    Priority: 'Medium',
    Date: '2023-08-26',
    Category: 'In progress',
  },
  {
    id: 30,
    owner: 5,
    Title: 'Review Presentation',
    Start: '4:00 PM',
    End: '5:30 PM',
    Priority: 'High',
    Date: '2023-08-27',
    Category: 'Done',
  },
  // Перший користувач
  {
    id: 31,
    owner: 1,
    Title: 'Submit Report',
    Start: '9:00 AM',
    End: '10:00 AM',
    Priority: 'Medium',
    Date: '2023-08-25',
    Category: 'To do',
  },
  {
    id: 32,
    owner: 1,
    Title: 'Online Meeting',
    Start: '2:00 PM',
    End: '3:30 PM',
    Priority: 'High',
    Date: '2023-08-26',
    Category: 'In progress',
  },
  {
    id: 33,
    owner: 1,
    Title: 'Write Code',
    Start: '11:00 AM',
    End: '1:00 PM',
    Priority: 'High',
    Date: '2023-08-27',
    Category: 'Done',
  },
  // Другий користувач
  {
    id: 34,
    owner: 2,
    Title: 'Review Presentation',
    Start: '3:00 PM',
    End: '4:30 PM',
    Priority: 'Medium',
    Date: '2023-08-25',
    Category: 'To do',
  },
  {
    id: 35,
    owner: 2,
    Title: 'Study New Technology',
    Start: '10:00 AM',
    End: '12:00 PM',
    Priority: 'High',
    Date: '2023-08-26',
    Category: 'In progress',
  },
  {
    id: 36,
    owner: 2,
    Title: 'Prepare Presentation',
    Start: '1:30 PM',
    End: '3:00 PM',
    Priority: 'High',
    Date: '2023-08-27',
    Category: 'Done',
  },
  // Третій користувач
  {
    id: 37,
    owner: 3,
    Title: 'Write Blog Post',
    Start: '4:00 PM',
    End: '6:00 PM',
    Priority: 'Medium',
    Date: '2023-08-25',
    Category: 'To do',
  },
  {
    id: 38,
    owner: 3,
    Title: 'Attend Workshop',
    Start: '2:00 PM',
    End: '4:30 PM',
    Priority: 'Low',
    Date: '2023-08-26',
    Category: 'In progress',
  },
  {
    id: 39,
    owner: 3,
    Title: 'Client Meeting',
    Start: '11:30 AM',
    End: '1:00 PM',
    Priority: 'High',
    Date: '2023-08-27',
    Category: 'Done',
  },
  // Четвертий користувач
  {
    id: 40,
    owner: 4,
    Title: 'Plan Vacation',
    Start: '9:00 AM',
    End: '11:00 AM',
    Priority: 'Medium',
    Date: '2023-08-25',
    Category: 'To do',
  },
];

export const reviews = [
  {
    id: 1,
    owner: 1,
    review: 'Great experience! The service was excellent.',
    rating: 5,
    avatarUrl: 'https://source.unsplash.com/random/150x150?user',
  },
  {
    id: 2,
    owner: 2,
    review: 'Nice place, friendly staff.',
    rating: 4,
    avatarUrl: 'https://source.unsplash.com/random/150x150?user',
  },
  {
    id: 3,
    owner: 3,
    review: 'Loved the food and atmosphere.',
    rating: 5,
    avatarUrl: 'https://source.unsplash.com/random/150x150?user',
  },
  {
    id: 4,
    owner: 4,
    review: 'Decent experience, could be better.',
    rating: 3,
    avatarUrl: 'https://source.unsplash.com/random/150x150?user',
  },
  {
    id: 5,
    owner: 5,
    review: 'Not satisfied with the service.',
    rating: 2,
    avatarUrl: 'https://source.unsplash.com/random/150x150?user',
  },
];
